# 开发环境
# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/community?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

  thymeleaf:
    cache: true

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000ms
    jedis:
      pool:
        max-active: 12
        max-wait: -1ms
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0

imgFilePath: C:/webresources/IMG/

lucenePath: C:/webresources/tmp/