server:
  port: 9000
  servlet:
    context-path: /

# 数据源配置
spring:
  profiles:
    active: dev # 使用的配置文件是开发环境的
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  jmx:
    default-domain: CodeDomain

# 个人配置文件  比如加盐的盐
personConfig:
#  加密用盐
  salt: adam

# 邮箱工具类配置信息
  mail:
    host: smtp.qq.com
    port: 587
    username: 123456789@qq.com
    password: asamjkjfkda